---
# defaults file for prometheus_installer
prometheus_install: True
prometheus_filename: prometheus-2.8.0.linux-amd64.tar.gz 
prometheus_etc_path: /etc/default/
prometheus_var_path: /var/lib/prometheus/
prometheus_data_path: "{{ prometheus_var_path }}data"
prometheus_conf_path: /etc/prometheus/
prometheus_bin_path: /usr/local/bin/
alertmanager_url: localhost:9093
prometheus_url: localhost:9090
prometheus_opts: "--storage.tsdb.retention=15d --web.enable-lifecycle"
rule_files_conf:
  - alert_rules.yml
wmi_exporter_sd_conf:
  - wmi_exporter.yml
node_exporter_sd_conf:
  - node_exporter.yml
