---
# defaults file for prometheus_installer
prometheus_install: True
prometheus_filename: prometheus-2.8.0.linux-amd64.tar.gz 
prometheus_etc_path: /etc/default/
prometheus_var_path: /var/lib/prometheus/
prometheus_data_path: "{{ prometheus_var_path }}data"
prometheus_conf_path: /etc/prometheus/
prometheus_bin_path: /usr/local/bin/
prometheus_opts: '--storage.tsdb.retention=15d --web.enable-lifecycle'
alertmanager_local_api: 127.0.0.1:9093
rule_files_conf:
  - alert_rules.yml
custom_sd_conf:
  - custom_sd.yml
