---
# defaults file for prometheus_installer
prometheus_install: True
prometheus_filename: prometheus-2.8.0.linux-amd64.tar.gz 
prometheus_etc_path: /etc/default/
prometheus_var_path: /var/lib/prometheus/
prometheus_data_path: "{{ prometheus_var_path }}data"
prometheus_conf_path: /etc/prometheus/
rule_files_conf_path: "{{ prometheus_conf_path }}alerts"
prometheus_bin_path: /usr/local/bin/
alertmanager_url: localhost:9093
prometheus_url: localhost:9090
prometheus_opts: "--storage.tsdb.retention=180d --web.enable-lifecycle --web.external-url=https://{{ ansible_default_ipv4['address'] }}:9090"
rule_files_conf:
  - alerts/*.yml
wmi_exporter_sd_conf:
  - wmi_exporter/*.yml
node_exporter_sd_conf:
  - node_exporter/*.yml
vmware_exporter_sd_conf:
  - vcenter.example.com
